---
- hosts: ios
  gather_facts: no
  connection: network_cli

  tasks:
  - name: REGISTER VTY CONFIG ON {{ ansible_ssh_host }}
    ios_command:
      commands:
        - show run | beg line vty
    register: vty

  - debug: var=vty.stdout_lines
