---
- hosts: ios
  gather_facts: no
  
  vars:
    log_servers:
      - logging 8.8.8.8
      - logging 8.8.4.4


  tasks:
  
  - name: RUN 'Set Logging'
    ios_config:
      commands: "{{ item }}"
    loop: "{{ log_servers }}"
        
  - name: "GET CONFIG"
    ios_command:
      commands:
        - show run | include logging [0-9]+\.[0-9]+\.[0-9]+\.[0-9]+
    register: log
    
  - debug: var=log.stdout_lines

      
  - name: RUN 'Remove Logging'
    ios_config:
      commands: "no {{ item }}"
    when:  "item not in log_servers"
    loop: "{{ log.stdout_lines[0] }}"

