---
- hosts: ios
  gather_facts: no
  
  vars:
    log_servers:
      - logging 8.8.8.8
      - logging 8.8.4.4


  tasks:
  - name: "capture existing logging servers"
    ios_command:
      commands:
        - show run | include logging 
    register: log_servers
    
  - debug: var=log_servers.stdout_lines
      
  - name: "Remove unnecessary ones"
    ios_config:
      commands: "no {{ item }}"
    when:  "item not in log_servers"
    loop: "{{ log_servers.stdout_lines[0]}}"

